<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIynTiqo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIynTiqo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIynTiqo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIynTiqo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIynTiqo\App_KernelDevDebugContainer([
    'container.build_hash' => 'IynTiqo',
    'container.build_id' => '1835ac77',
    'container.build_time' => 1581121641,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIynTiqo');
